import React, { useState } from 'react';
import { queueBlocker } from '../shared/models.js';

const statuses = [['working','กำลังทำ'],['checked','ตรวจครบ'],['partial','ของไม่ครบ'],['waiting','รอสินค้า'],['returned','ส่งกลับ']];
export default function OrderOperations({ order, busy, onRun, onDelete }) {
  const [store, setStore] = useState({ status: order.storeStatus || 'working', operator: order.storePackerName || '', checker: order.storeCheckerName || '', missing: (order.missingItems || []).join('\n'), note: '' });
  const [pack, setPack] = useState({ status: order.packStatus || 'working', operator: order.packPackerName || '', checker: order.packCheckerName || '', missing: (order.missingItems || []).join('\n'), note: '' });
  const [route, setRoute] = useState({ deliveryMethod: order.deliveryMethod || 'company_driver', workflowType: order.workflowType || 'store_route', shippingCarrier: order.shippingCarrier || '', reason: '' });
  const [booking, setBooking] = useState((order.bookingNumbers || [order.bookingNumber]).filter(Boolean).join('\n'));
  const blocker = queueBlocker(order); const lines = (value) => value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean);
  return <div className="sales-operations">
    <h3>คำสั่งดำเนินงาน</h3>
    <section><h4>เส้นทางการเตรียมงาน</h4><div className="sales-operation-grid"><label>ปลายทาง<select value={route.deliveryMethod} onChange={(e) => setRoute({ ...route, deliveryMethod: e.target.value })}><option value="company_driver">รถบริษัท</option><option value="grab_pickup">Grab</option><option value="customer_pickup">ลูกค้ารับเอง</option><option value="outstation">ต่างจังหวัด</option></select></label><label>ขั้นตอน<select value={route.workflowType} onChange={(e) => setRoute({ ...route, workflowType: e.target.value })}><option value="store_route">ส่งสโตร์ก่อน</option><option value="direct_pack">ส่งตรงห้องแพ็ค</option>{route.deliveryMethod === 'company_driver' && <option value="direct_driver">ส่งตรงคิวคนขับ</option>}</select></label>{route.deliveryMethod === 'outstation' && <label>บริษัทขนส่ง<input value={route.shippingCarrier} onChange={(e) => setRoute({ ...route, shippingCarrier: e.target.value })} /></label>}<label className="wide">เหตุผลเปลี่ยนเส้นทาง<input value={route.reason} onChange={(e) => setRoute({ ...route, reason: e.target.value })} /></label></div><button type="button" disabled={busy || !route.reason.trim()} onClick={() => onRun({ orderId: order.id, action: 'reroute', target: { deliveryMethod: route.deliveryMethod, workflowType: route.workflowType, shippingCarrier: route.shippingCarrier }, reason: route.reason })}>เปลี่ยนเส้นทางตามกฎต้นทาง</button></section>
    <Department title="สโตร์" prefix="store" value={store} setValue={setStore} busy={busy} onSubmit={() => onRun({ orderId: order.id, action: 'store_update', storeStatus: store.status, storePackerName: store.operator, storeCheckerName: store.checker, missingItems: lines(store.missing), storeWorkDetails: { note: store.note, checklist: { verified: true }, checkResult: store.status === 'checked' ? 'complete' : store.status } })} />
    <Department title="ห้องแพ็ค" prefix="pack" value={pack} setValue={setPack} busy={busy} onSubmit={() => onRun({ orderId: order.id, action: 'pack_update', packStatus: pack.status, packPackerName: pack.operator, packCheckerName: pack.checker, missingItems: lines(pack.missing), returnReason: pack.status === 'returned' ? pack.note : '', packWorkDetails: { note: pack.note, checklist: { verified: true }, checkResult: pack.status === 'checked' ? 'complete' : pack.status } })} />
    <section><h4>เลขใบสั่งจอง</h4><label>หนึ่งเลขต่อหนึ่งบรรทัด<textarea value={booking} onChange={(e) => setBooking(e.target.value)} /></label><button type="button" disabled={busy || !booking.trim()} onClick={() => onRun({ orderId: order.id, action: 'store_booking_update', bookingNumbers: lines(booking), entryStatus: 'confirmed' })}>ยืนยันเลขใบสั่งจอง</button></section>
    <section><h4>จ่ายงาน</h4><div className="sales-operation-actions"><button type="button" disabled={busy || Boolean(blocker)} title={blocker} onClick={() => onRun({ orderId: order.id, action: 'queue' })}>ส่งเข้าคิวคนขับ</button>{['grab_pickup','customer_pickup'].includes(order.deliveryMethod) && <button type="button" disabled={busy || order.queueStatus !== 'grab_ready'} onClick={() => onRun({ orderId: order.id, action: 'grab_pickup' })}>ยืนยันรับสินค้าแล้ว</button>}{order.complaint && <button type="button" disabled={busy} onClick={() => onRun({ orderId: order.id, action: 'complaint_resolve', note: 'ฝ่ายขายตรวจสอบและปิดปัญหาแล้ว' })}>ปิดปัญหา</button>}</div>{blocker && <p className="sales-blocker">ยังเข้าคิวไม่ได้: {blocker}</p>}</section>
    <section className="sales-danger-zone"><h4>จัดการรายการ</h4><div className="sales-operation-actions"><button type="button" disabled={busy} onClick={() => { const reason = window.prompt('เหตุผลที่นำออกจากห้องแพ็ค'); if (reason) onRun({ orderId: order.id, action: 'pack_archive', reason }); }}>นำออกจากห้องแพ็ค</button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`ลบออเดอร์ ${order.id}?`)) onDelete(order.id); }}>ลบออเดอร์</button></div></section>
  </div>;
}

function Department({ title, prefix, value, setValue, busy, onSubmit }) {
  const checkerRequired = ['checked','partial','waiting'].includes(value.status);
  return <section><h4>{title}</h4><div className="sales-operation-grid"><label>สถานะ<select value={value.status} onChange={(e) => setValue({ ...value, status: e.target.value })}>{statuses.map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label><label>ผู้ดำเนินการ<input value={value.operator} onChange={(e) => setValue({ ...value, operator: e.target.value })} /></label><label>ผู้ตรวจ<input value={value.checker} onChange={(e) => setValue({ ...value, checker: e.target.value })} /></label><label className="wide">ของที่ขาด (หนึ่งรายการต่อบรรทัด)<textarea value={value.missing} onChange={(e) => setValue({ ...value, missing: e.target.value })} /></label><label className="wide">หมายเหตุ<textarea value={value.note} onChange={(e) => setValue({ ...value, note: e.target.value })} /></label></div><button type="button" disabled={busy || (checkerRequired && !value.checker.trim())} onClick={onSubmit}>บันทึกสถานะ{title}ด้วยคำสั่ง `{prefix}_update`</button></section>;
}
