const { execSync } = require('child_process');
const fs = require('fs');
const out = [];
const result = execSync('git remote -v', { cwd: 'c:/Users/Office14/Documents/scan to sheet', encoding: 'utf8' });
out.push('=== Git Remote ===');
out.push(result);
const branch = execSync('git branch --show-current', { cwd: 'c:/Users/Office14/Documents/scan to sheet', encoding: 'utf8' });
out.push('=== Branch ===');
out.push(branch);
const log = execSync('git log --oneline -3', { cwd: 'c:/Users/Office14/Documents/scan to sheet', encoding: 'utf8' });
out.push('=== Last 3 commits ===');
out.push(log);
const status = execSync('git status --short', { cwd: 'c:/Users/Office14/Documents/scan to sheet', encoding: 'utf8' });
out.push('=== Status ===');
out.push(status);
fs.writeFileSync('c:/Users/Office14/Documents/scan to sheet/_git_output.txt', out.join('\n'), 'utf8');
