import { sendError } from './_auth.js';
import { allowedOrder, customerPayload, hillkoffRequest, recordSalesAudit, requireHillkoffSession, sendGatewayError, sendResult } from '../lib/hillkoffGateway.js';

const invalid = (res, code, message) => sendError(res, { status: 400, code, message });
export default async function handler(req, res) {
  try {
    const { session } = await requireHillkoffSession(req); const op = String(req.query?.op || ''); let result;
    if (op === 'me' && req.method === 'GET') result = await hillkoffRequest({ path: '/api/v1/me' });
    else if (op === 'customers' && req.method === 'GET') { const q = String(req.query?.q || '').trim().slice(0, 200); if (q.length < 3) return invalid(res, 'CUSTOMER_QUERY_TOO_SHORT', 'กรุณากรอกคำค้นหาอย่างน้อย 3 ตัวอักษร'); result = await hillkoffRequest({ path: '/api/v1/customers', query: { q } }); }
    else if (op === 'customers' && req.method === 'POST') { const customer = customerPayload(req.body?.customer); if (!/^[A-Za-z0-9._-]{1,120}$/.test(customer.id) || !customer.name) return invalid(res, 'CUSTOMER_INVALID', 'ข้อมูลลูกค้าไม่ครบถ้วน'); if (customer.mapUrl && !/^https?:\/\//i.test(customer.mapUrl)) return invalid(res, 'CUSTOMER_MAP_INVALID', 'ลิงก์แผนที่ไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/customers', method: 'POST', body: { customer } }); await recordSalesAudit({ session, action: 'customer_save', targetId: customer.id, outcome: result.status < 300 ? 'success' : 'rejected', requestId: result.requestId }).catch(() => {}); }
    else if (op === 'customer-history' && req.method === 'GET') { const customerId = String(req.query?.customerId || ''); if (!/^[A-Za-z0-9._-]{1,120}$/.test(customerId)) return invalid(res, 'CUSTOMER_ID_INVALID', 'รหัสลูกค้าไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/customers/history', query: { customerId } }); }
    else if (op === 'orders' && req.method === 'GET') { const q = String(req.query?.q || '').trim(); const id = String(req.query?.id || '').trim(); if ((!q && !id) || (q && id) || (q && q.length < 2) || (id && !/^[A-Za-z0-9._-]{1,120}$/.test(id))) return invalid(res, 'ORDER_QUERY_INVALID', 'คำค้นหาไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/orders', query: q ? { q, scope: req.query?.scope === 'outstation' ? 'outstation' : '' } : { id } }); }
    else if (op === 'orders' && req.method === 'POST') { const order = allowedOrder(req.body?.order); if (!/^[A-Za-z0-9._-]{1,120}$/.test(String(order.id || '')) || !/^[A-Za-z0-9._-]{1,120}$/.test(String(order.customerId || ''))) return invalid(res, 'ORDER_INVALID', 'ข้อมูลออเดอร์ไม่ครบถ้วน'); result = await hillkoffRequest({ path: '/api/v1/orders', method: 'POST', body: { order } }); await recordSalesAudit({ session, action: 'order_create', targetId: order.id, outcome: result.status < 300 ? 'success' : 'rejected', requestId: result.requestId }).catch(() => {}); }
    else if (op === 'dashboard' && req.method === 'POST') { const selectedDate = String(req.body?.selectedDate || '').slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(selectedDate)) return invalid(res, 'DATE_INVALID', 'วันที่ไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/orders/dispatch-dashboard', method: 'POST', body: { selectedDate } }); }
    else if (op === 'queue' && req.method === 'PATCH') { const orderId = String(req.body?.orderId || ''); if (!/^[A-Za-z0-9._-]{1,120}$/.test(orderId) || req.body?.action !== 'queue') return invalid(res, 'WORKFLOW_INVALID', 'คำสั่งจัดคิวไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/orders/workflow', method: 'PATCH', body: { orderId, action: 'queue' } }); await recordSalesAudit({ session, action: 'order_queue', targetId: orderId, outcome: result.status < 300 ? 'success' : 'rejected', requestId: result.requestId }).catch(() => {}); }
    else if (op === 'chiangmai-round' && req.method === 'PATCH') { const orderId = String(req.body?.orderId || ''); const roundCode = String(req.body?.roundCode || '').slice(0, 40); if (!/^[A-Za-z0-9._-]{1,120}$/.test(orderId) || !['tuesday', 'wednesday', 'friday'].includes(roundCode)) return invalid(res, 'ROUND_INVALID', 'ข้อมูลรอบเชียงใหม่ไม่ถูกต้อง'); result = await hillkoffRequest({ path: '/api/v1/orders/chiangmai-rounds', method: 'PATCH', body: { orderId, roundCode } }); await recordSalesAudit({ session, action: 'chiangmai_round_assign', targetId: orderId, outcome: result.status < 300 ? 'success' : 'rejected', requestId: result.requestId }).catch(() => {}); }
    else return sendError(res, { status: 405, code: 'OPERATION_NOT_ALLOWED', message: 'คำขอนี้ไม่ได้รับอนุญาต' });
    return sendResult(res, result);
  } catch (error) { return sendGatewayError(res, error); }
}
